server.port=${PORT:8080}
spring.application.name=hotel-operations-console-api

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_operations_console
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
